#!/bin/sh

mkdir ~/.config/ >/dev/null 2>&1
mkdir ~/.config/wifimanager >/dev/null 2>&1
cd ~/.config/wifimanager


addNetwork(){
	echo "What do you want to call your network?"
	read network
	echo "What is the network's SSID?"
	read ssid
	echo "What is the network's Password?"
	read password
	
	touch $network
	echo "ctrl_interface=/run/wpa_supplicant" > ./$network
	echo "update_config=1" >> ./$network
        doas wpa_passphrase $ssid $password >> ./$network

	echo "$network config file created"
}

listNetworks() {
	echo "$( ( ls ) )"
}

removeNetwork() {
	echo "Which network do you want to remove?"
	read rmnetwork
	rm ./$rmnetwork
}

connect () {
	echo "which network do you want to connect to?"
	read networkname
	devicename=`cat ./device`
	doas rm /run/wpa_supplicant/$devicename
	doas wpa_supplicant -B -i $devicename -c ./$networkname
}

setCard () {
	ip link
	echo "Which device is your wireless card name (Usually formatted at <wlpXsX>)"
	read deviceName
	touch device
	echo $deviceName > ./device
}

while :
do
	echo "Connect (c), Add new network (a), Remove network (r), List network config files (l), Set wireless card (s), quit (q)"
	read option

	if test $option = "a"
		then
		addNetwork
	elif test $option = "l"
		then
		listNetworks	
	elif test $option = "r"
		then
		removeNetwork
	elif test $option = "c"
		then
		connect
	elif test $option = "s"
		then
		setCard
	elif test $option = "q"
		then
		exit 0
	fi
done

